#!/usr/bin/env bash

SOURCE="$1"
HASH=$(sha256sum $SOURCE | awk '{ print $1; }')
CACHE_DIR="/tmp"

if [ ! -f "$CACHE_DIR"/"$HASH" ]
then
    head -n 1 "$SOURCE" | grep '#!/.*cash' >& /dev/null && \
        tail -n+2 "$SOURCE" | g++ -x c++ -o "$CACHE_DIR"/"$HASH" - 1>&2
fi

"$CACHE_DIR"/"$HASH"
